blog/urls.py
from django.urls import path
from django.views.generic.edit import DeleteView
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	delete,
	cross_off,
	uncross,
	

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	path('delete/<list_id>', delete, name = 'delete'),
    path('cross_off/<list_id>', cross_off, name = 'cross_off'),
    path('uncross/<list_id>', uncross, name = 'uncross'),
	#path('<slug>/delete',DeletePostView(),name='delete_post'),
]	

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,
    main_screen_view,
    adopt_animal_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,

)

urlpatterns = [
    path('/', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('',main_screen_view , name = 'main'),
    path('add/',adopt_animal_view , name = "add"),

	
	# REST-framework
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/account/', include('account.api.urls', 'account_api')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/models.py
from django.db import models



class InterestedPeople(models.Model):
	email = models.URLField(max_length=255)
	name = models.CharField(max_length=255)
	address = models.TextField(max_length=10000)
	number = models.IntegerField()
	animalname = models.TextField(max_length=10000)
	whatsapp = models.TextField(max_length=255)
	instagram = models.TextField(max_length=255)
	facebook = models.TextField(max_length=255)
 


	def __str__(self):
   	 return self.title + ' ' + self.display

# #Two tuple structure
# #The first element in each tuple is the value that will be stored in the database. The second element is displayed by the field’s form widget.
# #Tuple
# PRIORITY = [
# 	('L', 'Low'), #Tuple1
# 	('M', 'Medium'), #Tuple2
# 	('H', 'High'), #Tuple3
# ]

# class Question(models.Model):
# 	title		 			= models.CharField(max_length=60)
# 	question 				= models.TextField(max_length=400)
# 	priority 				= models.CharField(max_length=1, choices=PRIORITY)

# 	def __str__(self):
# 		return self.title


# 	class Meta:
# 		verbose_name = 'The Question'
# 		verbose_name_plural = 'Questions from People'

personal/forms.py
from .models import InterestedPeople
from django import forms

class InterestedPeopleForm(forms.ModelForm):
    class Meta:
        model =  InterestedPeople
        fields =['email','name','animalname','address','number','whatsapp','instagram','facebook']

personal/views.py
from django.shortcuts import render 
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from blog.views import get_blog_queryset
from blog.models import BlogPost

BLOG_POSTS_PER_PAGE = 10

def home_screen_view(request):
	
	context = {}

	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	


	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/home.html", context)

def main_screen_view(request):

	return render(request, "personal/main.html")


def adopt_animal_view(request):

	return render(request, "personal/add.html")

personal/templates/personal/add.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  {% load static %}
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="robots" content="">
    <meta name="description" content="">

<!-- FAVICONS ICON -->
    <link rel="icon" href="{% static 'images\favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images\favicon.png' %}">

<!-- MOBILE SPECIFIC -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- BOOTSTRAP STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- FONTAWESOME STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome/css/font-awesome.min.css' %}">


    <!-- OWL CAROUSEL STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- BOOTSTRAP SLECT BOX STYLE SHEET  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\bootstrap-select.min.css' %}">
    <!-- BOOTSTRAP SLIDER STYLE SHEET  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\bootstrap-slider.min.css' %}">

    <!-- BOOTSTRAP DATETIMEPICKER STYLE SHEET  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\bootstrap-datetimepicker.css' %}">

    <!-- MAGNIFIC POPUP STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\magnific-popup.min.css' %}">
    <!-- LOADER STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\loader.min.css' %}">
    <!-- MAIN STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\style.css' %}">
    <!-- FLATICON STYLE SHEET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\flaticon.min.css' %}">

    <!-- CLUSTER CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\cluster-css.css' %}">

    <link rel="stylesheet" href="{% static 'css\dropzone.css' %}">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous"> -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
    {% endif %}


<title>Add</title>
 <style media="screen">
    .btn-ph{
      background-color: #da552f !important;
    }
  </style>
  <script type="text/javascript">
    $.ajaxSetup({type: 'POST',headers: { "cache-control": "no-cache" }});
  </script>
</head>
<body class="bg-light">
  
<main role="main">
  <div class="container">

    <div class="my-5 py-5 d-flex flex-row justify-content-center rounded border shadow">

      <form class="w-75" action="{% url 'add' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!--script type="text/javascript">
          function getSlug(){
            var val = document.getElementById("title").value.replace(/[^a-zA-Z ]/g, "");
            document.getElementById("slug").value = val.toLowerCase().split(" ").join("-");
          }
        </script>-->
        <h2 class="text-center text-primary">Adopt your pet by filling this form </h2>
        <hr>

        <div class="form-group">
          <label for="url"> Email: </label>
          <input id="url" class="form-control" type="email" name="email">
        </div>

        

       <!-- <div class="form-group">
          <label for="slug">Slug : </label>
          <input id="slug" class="form-control" type="text" name="slug" maxlength="50">
          <small class="text-muted">Best practice is to not change slug unless its giving an error.</small>
        </div>-->

      


        <div class="form-group">
          <label for="owner"> Your Name : </label>
          <input id="owner" class="form-control" type="text" name="owner"  maxlength="255">
        </div>
        <div class="form-group">
          <label for="address">Address : </label>
          <input id="address" class="form-control" type="text" name="address"  maxlength="255">
        </div>
        <div class="form-group">
          <label for="number">Phone number : </label>
          <input id="number" class="form-control" type="number" name="number"  maxlength="10">
        </div>

        <!--<div class="form-group">
          <div class="custom-file">
            <input id="img" class="custom-file-input" type="file" name="back_image">
            <label class="custom-file-label" for="img">Add backgroud Image</label>
          </div>
        </div>

         <!--<div class="form-group">
          <div class="custom-file">
            <input id="ico" class="custom-file-input" type="file" name="icon">
            <label class="custom-file-label" for="ico">Add Icon</label>
          </div>
        </div>-->

        <div class="form-group">
          <label for="desc">Animal Name: </label>
          <input id="desc" class="form-control" ></textarea>
        </div>

        <div class="form-group">
          <label for="category">Choose a category:</label>
           <select id="category" name="category">
             <option value="DOG">Dog</option>
             <option value="CAT">Cat</option>
             <option value='OTHERS'>Others</option>
             <!-- <option value="Mehendi_artist">Mehendi artist</option>
             <option value="tattoo_artist">Tattoo artist</option>-->
           </select>
         </div>
 
         <div class="form-group">
          <label for="url"> Business Whatsapp link: </label>
          <input id="url" class="form-control" type="text" name="whatsapp">
        </div>
         
         <div class="form-group">
          <label for="url"> Instagram: </label>
          <input id="url" class="form-control" type="text" name="instagram">
        </div>
         <div class="form-group">
          <label for="url"> Facebook: </label>
          <input id="url" class="form-control" type="text" name="facebook">
        </div>
         <!--<div class="form-group">
          <label for="url"> Email: </label>
          <input id="url" class="form-control" type="email" name="email">
        </div>

        <div class="form-group">
          <label for="votes">Votes : </label>
          <input id="votes" class="form-control" type="number" min="1" max="1" name="votes" value="0" readonly>
        </div>-->

        <!--div class="form-group">
          <div class="custom-file">
            <input id="img" class="custom-file-input" type="file" name="imageone">
            <label class="custom-file-label" for="img">Add Image for gallery</label>
          </div>
        </div-->

        <!--<div class="form-group">
          <div class="custom-file">
            <input id="img" class="custom-file-input" type="file" name="imagetwo">
            <label class="custom-file-label" for="img">Add Image for gallery</label>
          </div>
        </div>

        <div class="form-group">
          <div class="custom-file">
            <input id="img" class="custom-file-input" type="file" name="imagethree">
            <label class="custom-file-label" for="img">Add Image for gallery</label>
          </div>
        </div>

        <div class="form-group">
          <div class="custom-file">
            <input id="img" class="custom-file-input" type="file" name="imagefour">
            <label class="custom-file-label" for="img">Add Image for gallery</label>
          </div>
        </div>-->



        <input class="btn btn-primary float-right" type="submit" value="Add">
      </form>
    </div>

  </div>
</main>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}
	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	.left-column{
		padding:0px;
	}
	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'codingwithmitch_logo1.png' %}" width="72" height="72">
					<p class="lead">You can add your animals for adoption from here.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->
	
			
			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
						<div class="d-grid gap-2">
							<li><a href="{% url 'add' %}">Adopt</a></li>

						  </div>
					</div>
					
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
					
				</div>
			{% endif %}

			
			<!-- End Blog posts-->
		
			<!-- Pagination -->
			{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->



		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'codingwithmitch_logo1.png' %}" width="72" height="72">
				<p class="lead">You can add your animals for adoption from here.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}